server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/campus_events
spring.data.mongodb.database=campus_events

# CORS
spring.web.cors.allowed-origins=http://localhost:5173

# Logging
logging.level.com.campus=DEBUG

# Swagger / SpringDoc
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
